[package]
name = "ron-bench"
version = "0.1.0"
edition = "2018"

default-run = "ron-bench"

[dependencies]
criterion = { version = "*", features = ["html_reports"] }
ron = { git = "https://github.com/ron-rs/ron" }
ron-reboot = { git = "https://github.com/ron-rs/ron-reboot" }
serde_json = "*"
